version: '3.8'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=karldb
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql